import './globals.css'
import { Inter, Montserrat } from 'next/font/google'
import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ECommerce Application Demo',
  description: 'This is ecommerce app Generated by create next app',
}
const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" class="light">
      <body className={montserrat.className}>
      <Header />
        {children}
      </body>
    </html>
  )
}
